apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: poddefaults.kubeflow.org
spec:
  group: kubeflow.org
  names:
    kind: PodDefault
    plural: poddefaults
    singular: poddefault
  scope: Namespaced
  # https://github.com/kubeflow/kubeflow/issues/6428#issue-1188731992
  preserveUnknownFields: false
  versions: 
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              desc:
                type: string
              serviceAccountName:
                type: string
              automountServiceAccountToken:
                type: boolean
              env:
                items:
                  type: object
                type: array
              envFrom:
                items:
                  type: object
                type: array
              selector:
                type: object
              volumeMounts:
                items:
                  type: object
                type: array
              volumes:
                items:
                  type: object
                type: array
            required:
            - selector
            type: object
          status:
            type: object
        type: object
